services:
  auth_db:
    image: postgres:latest
    container_name: auth_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_be_user
      POSTGRES_PASSWORD: LaNtrYSOctIsMycionAlPTiCKEYema
    volumes:
      - ./data/auth:/var/lib/postgresql/data
      - ./init/auth:/docker-entrypoint-initdb.d:ro
    networks:
      - pragma-network
  loan_application_db:
    image: postgres:latest
    container_name: loan_applications_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: applications_db
      POSTGRES_USER: application_be_user
      POSTGRES_PASSWORD: sTRuDYSPEADrECTfuLTarGoNdIFIch
    volumes:
      - ./data/loan:/var/lib/postgresql/data
      - ./init/loan:/docker-entrypoint-initdb.d:ro
    networks:
      - pragma-network
networks:
  pragma-network:
    driver: bridge